# Setup
title:               システム行動学研究会
tagline:             'システム行動学研究会　(Systems Ethology)'
description:         'システム行動学研究会のHPです。システム行動学とは、行動をシステムとして捉え、分野を問わずさまざまなアプローチで解明していこうとする学問です。'
url:                 "https://systemsethology.github.io"
baseurl:             "/website"
paginate:            5
permalink:           pretty
markdown:            kramdown

style: /assets/css/style.css

remote_theme: jekyll-theme-lanyon
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# About/contact
author:
  name:              Hayato M. Yamanouchi
  url:               https://github.com/HMYamano
  email:             haya.m.yamano.neuro@gmail.com


# Custom vars
version:             beta version
google_analytics_id: G-E6R8GNZD98
